######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 28 16:03:50 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
