######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 3 16:54:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
