######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 2 13:47:27 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
