######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 1 11:34:20 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
