######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 5 00:28:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
