######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 4 17:54:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
