######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 29 03:19:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
