######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 17 16:36:00 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
