######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 31 08:09:25 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h PvApi.h
SOURCES += main.cpp
